FROM node:16-alpine

RUN npm install -g nodemon
# hadolint ignore=DL3018
RUN apk --no-cache add bash curl less tini vim make
SHELL ["/bin/bash", "-o", "pipefail", "-o", "errexit", "-u", "-c"]

WORKDIR /usr/local/src/app

# Allow yarn/npm to create ./node_modules
RUN chown node:node .

# Copy specific things so that we can keep the image as small as possible
# without relying on each repo to include a .dockerignore file.
COPY --chown=node:node ./ ./

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

USER root

# Install ALL dependencies. We need devDependencies for the build command.
# removed --frozen-lockfile from yarn install
RUN yarn install --production=false --ignore-scripts --non-interactive --no-cache

ENV NODE_ENV=development

# Bundle app source
COPY . .

EXPOSE 5000

# If any Node flags are needed, they can be set in the NODE_OPTIONS env variable.
CMD ["tini", "--", "yarn", "start:dev"]