
version: '3.4'
networks:
  reaction:
    external:
      name: reaction.localhost
services:
  rest_api:
    image: luiscelano/ec-rest-api:1.0.0-beta
    build:
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rest_api.entrypoints=http"
      - "traefik.http.routers.rest_api.rule=Host(`restapi.lulisgt.com`)"
      - "traefik.http.middlewares.rest_api-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.api.middlewares=api-https-redirect"
      #- "traefik.http.middlewares.web-https-redirect.replacepathregex.regex=^/pages/lulis-care"
      #- "traefik.http.middlewares.web-https-redirect.replacepathregex.replacement=/es"
      - "traefik.http.routers.rest_api-secure.entrypoints=https"
      - "traefik.http.routers.rest_api-secure.rule=Host(`restapi.lulisgt.com`)"
      - "traefik.http.routers.rest_api-secure.tls=true"
      - "traefik.http.routers.rest_api-secure.service=api"
      - "traefik.http.services.rest_api.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"
      - "traefik.http.routers.rest_api-secure.tls.certresolver=le"
      - "traefik.http.routers.rest_api-secure.tls.domains[0].main=lulisgt.com"
      - "traefik.http.routers.rest_api-secure.tls.domains[0].sans=*.lulisgt.com"

    networks:
        default:
        reaction:
    ports:
      - 5000:5000