
version: '3.4'
networks:
  web:
    external:
      name: web
services:
  rest_api:
    image: luiscelano/ec-rest-api:1.0.0-beta
    build:
      context: .
    networks:
        web:
    volumes:
      - ./package-lock.json:/usr/local/src/app/package-lock.json
      - ./package.json:/usr/local/src/app/package.json
    ports:
      - 5000:5000