query accounts($groupIds: [ID], $query: String, $notInAnyGroups: Boolean, $after: ConnectionCursor, $before: ConnectionCursor, $first: ConnectionLimitInt, $last: ConnectionLimitInt, $offset: Int, $sortOrder: SortOrder, $sortBy: AccountSortByField){
    accounts(groupIds: $groupIds, query: $query, notInAnyGroups: $notInAnyGroups, after: $after, before: $before, first: $first, last: $last, offset: $offset, sortOrder: $sortOrder, sortBy: $sortBy){
        edges{
            cursor
            node{
                _id
                addressBook(after: $after, before: $before, first: $first, last: $last, offset: $offset){
                    edges{
                        cursor
                    }
                    nodes{
                        _id
                        description
                        address
                        reference
                        geolocation{
                            latitude
                            longitude
                        }
                        metaddress{
                            administrative_area_level_1
                            administrative_area_level_2
                            neighborhood
                            street_address
                            sublocality
                            distance{
                                value
                                text
                            }
                        }
                    }
                    pageInfo{
                        endCursor
                        hasNextPage
                        hasPreviousPage
                        startCursor
                    }
                    totalCount
                }
                bio
                createdAt
                currency{
                    _id
                    code
                    decimal
                    format
                    rate
                    scale
                    symbol
                    thousand
                }
                emailRecords{
                    address
                    provides
                    verified
                }
                firstName
                language
                phone
                lastName
                metafields{
                    description
                    key
                    namespace
                    scope
                    value
                    valueType
                }
                name
                note
                picture
                preferences
                primaryEmailAddress
                updatedAt
                userId
                username
            }
        }
        nodes{
            _id
            addressBook(after: $after, before: $before, first: $first, last: $last, offset: $offset){
                totalCount
            }
            bio
            createdAt
            currency{
                _id
                code
                decimal
                format
                rate
                scale
                symbol
                thousand
            }
            emailRecords{
                address
                provides
                verified
            }
            firstName
            language
            phone
            lastName
            name
            note
            picture
            preferences
            primaryEmailAddress
            updatedAt
            userId
            username
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
        totalCount
    }
}