query getFlatRateFulfillmentRestrictions($shopId: ID!, $after: ConnectionCursor, $before: ConnectionCursor, $first: ConnectionLimitInt, $last: ConnectionLimitInt, $offset: Int, $sortOrder: SortOrder, $sortBy: FlatRateFulfillmentRestrictionSortByField){
    getFlatRateFulfillmentRestrictions(shopId: $shopId, after: $after, before: $before, first: $first, last: $last, offset: $offset, sortOrder: $sortOrder, sortBy: $sortBy){
        edges{
            cursor
            node{
                _id
                attributes{
                    operator
                    property
                    propertyType
                    value
                }
                destination{
                    country
                    postal
                    region
                }
                methodIds
                shopId
                type
            }
        }
        nodes{
            _id
            attributes{
                operator
                property
                propertyType
                value
            }
            destination{
                country
                postal
                region
            }
            methodIds
            shopId
            type
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
        totalCount
    }
}