query navigationItemsByShopId($shopId: ID!, $after: ConnectionCursor, $before: ConnectionCursor, $first: ConnectionLimitInt, $last: ConnectionLimitInt, $offset: Int, $sortOrder: SortOrder, $sortBy: NavigationItemSortByField){
    navigationItemsByShopId(shopId: $shopId, after: $after, before: $before, first: $first, last: $last, offset: $offset, sortOrder: $sortOrder, sortBy: $sortBy){
        edges{
            cursor
            node{
                _id
                createdAt
                data{
                    classNames
                    content{
                        language
                        value
                    }
                    contentForLanguage
                    isUrlRelative
                    shouldOpenInNewWindow
                    url
                }
                draftData{
                    classNames
                    content{
                        language
                        value
                    }
                    contentForLanguage
                    isUrlRelative
                    shouldOpenInNewWindow
                    url
                }
                hasUnpublishedChanges
                metadata
                shopId
            }
        }
        nodes{
            _id
            createdAt
            data{
                classNames
                contentForLanguage
                isUrlRelative
                shouldOpenInNewWindow
                url
            }
            draftData{
                classNames
                contentForLanguage
                isUrlRelative
                shouldOpenInNewWindow
                url
            }
            hasUnpublishedChanges
            metadata
            shopId
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
        totalCount
    }
}