query surcharges($language: String!, $language1: String!, $shopId: ID!, $after: ConnectionCursor, $before: ConnectionCursor, $first: ConnectionLimitInt, $last: ConnectionLimitInt, $offset: Int, $sortOrder: SortOrder, $sortBy: SurchargeSortByField){
    surcharges(shopId: $shopId, after: $after, before: $before, first: $first, last: $last, offset: $offset, sortOrder: $sortOrder, sortBy: $sortBy){
        edges{
            cursor
            node{
                _id
                amount{
                    amount
                    currency{
                        _id
                        code
                        decimal
                        format
                        rate
                        scale
                        symbol
                        thousand
                    }
                    displayAmount
                }
                attributes{
                    operator
                    property
                    propertyType
                    value
                }
                createdAt
                destination{
                    country
                    postal
                    region
                }
                message(language: $language)
                messagesByLanguage{
                    content
                    language
                }
                methodIds
                shopId
                type
                updatedAt
            }
        }
        nodes{
            _id
            amount{
                amount
                displayAmount
            }
            attributes{
                operator
                property
                propertyType
                value
            }
            createdAt
            destination{
                country
                postal
                region
            }
            message(language: $language1)
            messagesByLanguage{
                content
                language
            }
            methodIds
            shopId
            type
            updatedAt
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
        totalCount
    }
}