query surchargeById($language: String!, $shopId: ID!, $surchargeId: ID!){
    surchargeById(shopId: $shopId, surchargeId: $surchargeId){
        _id
        amount{
            amount
            currency{
                _id
                code
                decimal
                format
                rate
                scale
                symbol
                thousand
            }
            displayAmount
        }
        attributes{
            operator
            property
            propertyType
            value
        }
        createdAt
        destination{
            country
            postal
            region
        }
        message(language: $language)
        messagesByLanguage{
            content
            language
        }
        methodIds
        shopId
        type
        updatedAt
    }
}